apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petclinic-native
  description: Spring Petclinic
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of: petclinic-native'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: tanzu-web